/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author ASUS
 */
public class frameUtama extends javax.swing.JFrame {

    /**
     * Creates new form frameUtama
     */
    public frameUtama() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnFormPembelian = new javax.swing.JButton();
        btnFormUser = new javax.swing.JButton();
        btnFormBarang = new javax.swing.JButton();
        btnFormPenjualan = new javax.swing.JButton();
        btnFormSupplier = new javax.swing.JButton();
        btnFormPelanggan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("MAIN MENU");

        btnFormPembelian.setText("Form Pembelian");
        btnFormPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPembelianActionPerformed(evt);
            }
        });

        btnFormUser.setText("Form User");
        btnFormUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormUserActionPerformed(evt);
            }
        });

        btnFormBarang.setText("Form Barang");
        btnFormBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormBarangActionPerformed(evt);
            }
        });

        btnFormPenjualan.setText("Form Penjualan");
        btnFormPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPenjualanActionPerformed(evt);
            }
        });

        btnFormSupplier.setText("Form Supplier");
        btnFormSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormSupplierActionPerformed(evt);
            }
        });

        btnFormPelanggan.setText("Form Pelanggan");
        btnFormPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFormUser, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFormPembelian)
                            .addComponent(btnFormPelanggan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFormSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFormPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFormBarang))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFormBarang, btnFormPelanggan, btnFormPembelian, btnFormPenjualan, btnFormSupplier, btnFormUser});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormUser)
                    .addComponent(btnFormBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormPembelian)
                    .addComponent(btnFormPenjualan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormSupplier)
                    .addComponent(btnFormPelanggan))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnFormBarang, btnFormPelanggan, btnFormPembelian, btnFormPenjualan, btnFormSupplier, btnFormUser});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormUserActionPerformed
        new frameUser().setVisible(true);
    }//GEN-LAST:event_btnFormUserActionPerformed

    private void btnFormBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormBarangActionPerformed
        new frameBarang().setVisible(true);
    }//GEN-LAST:event_btnFormBarangActionPerformed

    private void btnFormPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPenjualanActionPerformed
        new framePenjualan().setVisible(true);
    }//GEN-LAST:event_btnFormPenjualanActionPerformed

    private void btnFormSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormSupplierActionPerformed
        new frameSupplier().setVisible(true);
    }//GEN-LAST:event_btnFormSupplierActionPerformed

    private void btnFormPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPelangganActionPerformed
        new framePelanggan().setVisible(true);
    }//GEN-LAST:event_btnFormPelangganActionPerformed

    private void btnFormPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormPembelianActionPerformed
        new framePembelian().setVisible(true);
    }//GEN-LAST:event_btnFormPembelianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormBarang;
    private javax.swing.JButton btnFormPelanggan;
    private javax.swing.JButton btnFormPembelian;
    private javax.swing.JButton btnFormPenjualan;
    private javax.swing.JButton btnFormSupplier;
    private javax.swing.JButton btnFormUser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
